// <auto-generated />
namespace News.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Url_OnDatas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Url_OnDatas));
        
        string IMigrationMetadata.Id
        {
            get { return "201611161942252_Url_OnDatas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
