// <auto-generated />
namespace News.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class GalerySystem_06092016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(GalerySystem_06092016));
        
        string IMigrationMetadata.Id
        {
            get { return "201609062003305_GalerySystem_06092016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
